### PR TITLE
No introduction, just a dream

### PR DESCRIPTION
**Pull request by boehs**
I don't know how you will get where you are going, but I believe I dream of going some place similar. I want to help.

I am yet to finish ingesting agora and all it's layers, but with this pull request I testify that I want to be a part of it and I am committing to understanding it.

With that I digitally sign the contract

### CODE REVIEW

**Comment by flancian** [comment]
Thank you for the PR. Welcome to the Agora! Your profile should be live in a few minutes.

**Comment by flancian** [comment]
Done :)

https://anagora.org/@evan

By default all READMEs in the repository get rendered in your user page, it seems you use Svelte? That's cool, I wanted to learn it :) I will probably push a fix so only the README in the garden's root gets rendered there.

Thank you for your beautiful words!

**Comment by flancian** [comment]
Oh, I forgot to say (this should be in a 'welcome to the Agora' node I guess): if you add an index.md to your repo, the Agora will render it in the homepage (https://anagora.org).

**Comment by boehs** [comment]
> Done :)
> 
> https://anagora.org/@evan
> 
> By default all READMEs in the repository get rendered in your user page, it seems you use Svelte? That's cool, I wanted to learn it :) I will probably push a fix so only the README in the garden's root gets rendered there.
> 
> Thank you for your beautiful words!

Oops, was wondering why it was doing that! I was messing around with republishing my website in svelte but was encountering all sorts of issues with routing (that readme being an artifact of that), and I decided that while I love svelte, it was not right for the project, and so I ended up here.

**Pull request merged**
