### PR TITLE
add Jayu

### PR DESCRIPTION
**Pull request by jayu-eleutheria**
(I hereby accept [https://anagora.org/contract](https://anagora.org/contract))

### CODE REVIEW

**Comment by flancian** [comment]
Welcome to the Agora, my friend!

https://anagora.org/@jayu will be live shortly, updates to your garden should be reflected in the Agora within ~30 seconds of pushing, plus sometimes caching delay (when a page is accessed it gets cached for a while).

Let me know if you need anything!

**Comment by flancian** [comment]
I had issues merging the PR in github for no clear reason (not clear to me anyway :)) so I merged 'by hand'. Thank you for your PR!

**Comment by flancian** [comment]
Out of curiosity: how do you use the leading ^numbers in your garden? What do they stand for/what do they mean/how should they render? :)

**Comment by jayu-eleutheria** [comment]
Thank you! I'm very happy to join the Agora.

These ^numbers are custom block IDs. They're a relatively unknown/unused feature in Obsidian, as most people do not need to customize block IDs, but to me they're a necessity:

I use IDs for all elements in all my digital (and analogical) gardens, irrespective of which systems/apps I'm using to support them. Their main purpose is for cross-references between my gardens that do not depend on the elements' titles or contents (similar to Zettelkasten IDs). 

I have my own syntax, though I tend to use the native syntax (and translate it to my own) when an app already has block IDs, like Obsidian.

They're not useful for other people, so I guess they should not be rendered in the Agora (or simply ignored as a particular quirk of my subnodes).

**Comment by jayu-eleutheria** [comment]
I always write the conventions I use for a garden inside the garden itself (the Meta, as it appears in my index), so they'll appear soon there.

I'm gonna close this PR, but if you have any questions, feel free to contact me anywhere you'd like :D

**Pull request closed without merging**
