### PR TITLE
Dockerfile cleanup

### PR DESCRIPTION
**Pull request by codegod100**

### CODE REVIEW

**Comment by codegod100** [comment]
Might want to use [434f234] I was using old debian image to create so was giving error

**Comment by codegod100** [comment]
http://dev.anagora.org is running container I made from [434f234](https://github.com/flancian/agora/pull/22/commits/434f234d6d504e6dde1710af137a55ea176f62de)

**Comment by codegod100** [comment]
force pushed to right sha. image available at https://hub.docker.com/r/moonlion/agora

**Comment by flancian** [comment]
Thank you for your contribution! I merged this with one I had pending which changes the Agora to work with a volume.

**Pull request merged**
